### ISSUE TITLE
Reorganize folder structure

### ISSUE THREAD

**Issue by prodigion** [kulttuuri/DiscordNotifications#16]
Can all the files be moved to the base folder so that this can be directly included in our extensions folder?

**Comment by kulttuuri** [comment]
What kind of folder structure do you mean?

**Comment by prodigion** [comment]
Move everything into the same top-level folder.

**Comment by kulttuuri** [comment]
Done! Also renamed the repository to be the same name as the extension so this can be directly cloned into your mediawiki extensions folder :)
