### ISSUE TITLE
Protect page error

### ISSUE THREAD

**Issue by BlackDuke07** [kulttuuri/DiscordNotifications#18]
When I try to protect a page with DiscordNotifications installed I get the following error:

[W4N5pjbmAHgAjUUkWSvWIAAAABA] /index.php?title=Main_Page&action=protect ArgumentCountError from line 212 of /home/retror/public_html/extensions/DiscordNotifications/DiscordNotificationsCore.php: Too few arguments to function DiscordNotifications::discord_article_protected(), 4 passed in /home/retror/public_html/includes/Hooks.php on line 177 and exactly 5 expected

Backtrace:

#0 /home/retror/public_html/includes/Hooks.php(177): DiscordNotifications::discord_article_protected(WikiPage, User, array, string)
#1 /home/retror/public_html/includes/Hooks.php(205): Hooks::callHook(string, array, array, NULL)
#2 /home/retror/public_html/includes/page/WikiPage.php(2521): Hooks::run(string, array)
#3 /home/retror/public_html/includes/page/Article.php(2593): WikiPage->doUpdateRestrictions(array, array, boolean, string, User)
#4 /home/retror/public_html/includes/ProtectionForm.php(312): Article->doUpdateRestrictions(array, array, boolean, string, User)
#5 /home/retror/public_html/includes/ProtectionForm.php(187): ProtectionForm->save()
#6 /home/retror/public_html/includes/page/Article.php(1544): ProtectionForm->execute()
#7 /home/retror/public_html/includes/actions/ProtectAction.php(52): Article->protect()
#8 /home/retror/public_html/includes/MediaWiki.php(500): ProtectAction->show()
#9 /home/retror/public_html/includes/MediaWiki.php(294): MediaWiki->performAction(Article, Title)
#10 /home/retror/public_html/includes/MediaWiki.php(861): MediaWiki->performRequest()
#11 /home/retror/public_html/includes/MediaWiki.php(524): MediaWiki->main()
#12 /home/retror/public_html/index.php(42): MediaWiki->run()
#13 {main}

**Comment by kulttuuri** [comment]
Can you try removing the parameter $moveonly = false from the function call on file DiscordNotificationsCore and let me know if it works after that?

So change this:
`static function discord_article_protected($article = null, $user = null, $protect = false, $reason = "", $moveonly = false)`

To this:
`static function discord_article_protected($article = null, $user = null, $protect = false, $reason = "")`

I have a feeling that the last parameter is not actually being passed by MediaWiki Core and that's causing the issue.

**Comment by kulttuuri** [comment]
Closing as no reply.
