### ISSUE TITLE
Support for multiple languages

### ISSUE THREAD

**Issue by DFelten** [kulttuuri/DiscordNotifications#20]
Thanks for this great extension! We're hosting a German site and so we need to translate the messages into German. 

So I've created a fork of the branch and inserted the support for multiple languages. I followed the MediaWiki conventions and outsourced the translations into i18n files.

You are welcome to take my changes if you want and everything is correct: [Fork for supporting multple languages](https://github.com/DFelten/DiscordNotifications/tree/support-for-multiple-languages)

**Comment by kulttuuri** [comment]
Fantastic, looks good! Could you create a pull request for this? :)

**Comment by kulttuuri** [comment]
Nevermind, I can just diff the changes from you in the repo. I'll work on this next week while I prepare new release with other features out, too. Thanks again! 👍

**Comment by kulttuuri** [comment]
Implemented in 1.06, thank you for this! :) I've also added you as a contributor to end of the readme file.

**Comment by DFelten** [comment]
Great, thanks for adding my changes to your repository :)
