### ISSUE TITLE
Response text from server is displayed on the page

### ISSUE THREAD

**Issue by ciencia** [kulttuuri/DiscordNotifications#26]
After reverting a bunch of edits in quick succession, some pages returned a strange text at the top of the page. It was a JSON with 3 keys, one of them was "You are being rate limited".

At first I though it was some MediaWiki feature like poolcounter, but strangely, after doing a grep of all the code, I wasn't unable to find that text.

Now I think the text comes from Discord, and the response is simply sent to stdout. Normally, sending something to a webhook doesn't print anything, but because I was doing mass actions, it was displaying that text about rate limiting.

Apparently curl outputs response body to stdout. That should be changed, specially if Discord starts output something in the future... http://biostall.com/removing-unwanted-output-from-a-curl-transfer-in-php/

**Comment by kulttuuri** [comment]
Should be fixed in 1.07, can you check that it works? :)

**Comment by kulttuuri** [comment]
Closing.
