### ISSUE TITLE
i18n in notifications should use the wiki's language, not the user language

### ISSUE THREAD

**Issue by ciencia** [kulttuuri/DiscordNotifications#27]
Apparently, the extension is using the language from preferences of the user doing the action (edit), instead of the wiki's language ( [$wgContLang](https://www.mediawiki.org/wiki/Manual:$wgContLang) ) resulting in some messages being sent in a different language.

![imagen](https://user-images.githubusercontent.com/44133/52537858-9e2cd680-2d6b-11e9-9dc2-02f356a80281.png)

**Comment by kulttuuri** [comment]
Hi! Thanks for the heads-up. This should now be fixed in release 1.07 (latest), can you check that it works? :)

**Comment by kulttuuri** [comment]
Closing.
