### ISSUE TITLE
DiscordNotifications publishes notifications about suppressionlog entries

### ISSUE THREAD

**Issue by NDKilla** [kulttuuri/DiscordNotifications#30]
This extension publishes non-public logs. When users are blocked and hidden or an article / revision is deleted and suppressed, log entries are still published.

See below picture for a supressionlog entry showing up in our discord server. Note that this was a test but I was confirming after somebody else said it did it with legitimate logs and had to delete the bots messages.

![image](https://user-images.githubusercontent.com/1078941/56458924-aea89100-635a-11e9-9b02-12f9ce0ca313.png)

**Comment by multicon** [comment]
Did you disable the $wgDiscordNotificationRemovedArticle action?

**Comment by paladox** [comment]
@multicon hi, We have not disabled that because we don't want to disable deletion notifications. It's more about RevisionDeletion actions https://www.mediawiki.org/wiki/Manual:RevisionDelete

**Comment by kulttuuri** [comment]
Merged!
