### ISSUE TITLE
Null-edit triggers webhook

### ISSUE THREAD

**Issue by MPThLee** [kulttuuri/DiscordNotifications#32]
On 1.31.1, Extension is on master branch

`pencil Bot (block | groups | talk | contribs) has edited article Article (edit | delete | history | diff) Summary: Pywikibot touch edit (+0 bytes)`
Example is by Pywikibot touch.py. but also triggered by user null edits.

----

> $revision: Revision object of the saved content. If the save did not result in the creation of a new revision (e.g. the submission was equal to the latest revision), this parameter may be null (null edits, or "no-op"). However, there are reports (see phab:T128838) that it's instead set to that latest revision.

May this helps to fix bug.

**Comment by MPThLee** [comment]
Seems it need to call `$revision->getPrevious()`, not `$article->getRevision()->getPrevious()` in [here](https://github.com/kulttuuri/DiscordNotifications/blob/7bda2ce6e2a0ccc4cca860949525d3613ac5df9a/DiscordNotificationsCore.php#L138).

**Comment by kulttuuri** [comment]
Yeah, calling either always returns an object instead of being NULL ever. They might have changed this in MediaWiki. Might need to check this with some other way...

**Comment by kulttuuri** [comment]
Anyway, I've committed a check to check for both occurrences! Might have been fixed in more later MediaWiki version (I am using 1.29.1).

If you @MPThLee could verify that this indeed fixes the problem, that would be super helpful! :)

**Comment by MPThLee** [comment]
It is still triggerd on my side.
But another discord extension which required 1.31+ is not triggred on null edit. [with this code..?](https://github.com/jaydenkieran/mw-discord/blob/master/src/DiscordHooks.php#L30-L33)

**Comment by kulttuuri** [comment]
Cool, will check if that same code could be used here.

**Comment by kulttuuri** [comment]
Fix pushed out to master, can you check once again? :)

**Comment by kulttuuri** [comment]
@MPThLee

**Comment by MPThLee** [comment]
Sorry for delay reply, I quite busy on last week.
The workaround is worked, null edits are not showing up now.

**Comment by kulttuuri** [comment]
Fantastic, great to hear! :)
