### ISSUE TITLE
PHP Warning: count(): Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by MPThLee** [kulttuuri/DiscordNotifications#34]
`ErrorException DiscordNotificationsCore.php:MWExceptionHandler in handleError`
`PHP Warning: count(): Parameter must be an array or an object that implements Countable
php`

MW 1.31.1, on master branch.

At [here](https://github.com/kulttuuri/DiscordNotifications/blob/8111d2a38e9f9cccd403a3473450e6e76dc01292/DiscordNotificationsCore.php#L428) and [here](https://github.com/kulttuuri/DiscordNotifications/blob/8111d2a38e9f9cccd403a3473450e6e76dc01292/DiscordNotificationsCore.php#L435)

**Comment by kulttuuri** [comment]
This seems to be caused by more newer PHP version throwing exception when that variable is empty. I'll try to come up with some fix for this.

**Comment by kulttuuri** [comment]
Better conditionals added now. Can you check that it works now? :)

**Comment by MPThLee** [comment]
I'm using php 7.3.5 right now, and this is fixed on master branch.

**Comment by kulttuuri** [comment]
Fantastic. Thank you very much on checking back on this!
