### ISSUE TITLE
Running certain maintenance scripts echos useless PHP warning for extension

### ISSUE THREAD

**Issue by charitwo** [kulttuuri/DiscordNotifications#38]
`PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /var/www/<website>/htdocs/w/extensions/DiscordNotifications/DiscordNotificationsCore.php on line 120`

not the first time this extension has affected core features negatively

**Comment by kulttuuri** [comment]
Should be fixed in latest commit, now checking if object is an array before using count function on it.
