### ISSUE TITLE
More detailed "user group" event

### ISSUE THREAD

**Issue by Linedwell** [kulttuuri/DiscordNotifications#45]
This request is an enhancement suggestion to my previous request #28 .

In order to get enough information to know which userrights have been changed, it would be useful to mention in the userright change notification the old groups aswell as the new ones.

Currently we have something like:
>UserA (block | groups | talk | contribs) has changed user groups for UserB (block | groups | talk | contribs). New groups: abusefilter, bureaucrat, sysop, checkuser

What I suggest would be to have someting like:
>UserA (block | groups | talk | contribs) has changed user groups for UserB (block | groups | talk | contribs). Old groups: abusefilter, bureaucrat, sysop ; New groups: abusefilter, bureaucrat, sysop, checkuser

**Comment by kulttuuri** [comment]
Added in latest commit!

**Comment by kulttuuri** [comment]
@lens0021 I added the new translation to korean file. Can you translate it? It's this one:
"discordnotifications-change-user-groups-with-old": "%s has changed user groups for %s. Old groups: %s. New groups: %s",

**Comment by Linedwell** [comment]
Thank you very much
