### ISSUE TITLE
Using translatewiki.net

### ISSUE THREAD

**Issue by lens0021** [kulttuuri/DiscordNotifications#49]
Making the repository use https://translatewiki.net is quite simple and effective. If done, the messages in this extension can be displayed at https://translatewiki.net, volunteer translators around the world can translate messages and bot @translatewiki can watch all updates and automatically make commits.

But there are pre-requirements. See https://translatewiki.net/wiki/Setup_of_a_new_project for details. Anyway, I made a todo list:

- (Optional) Creating a task on https://phabricator.wikimedia.org/ is a good idea I think.
- 1\. Follow [the guideline for system messages](https://www.mediawiki.org/wiki/Localisation#Adding_new_messages).
  - [x] 1-1. I recommend replacing `%s` with `$1`.
  - [x] 1-2. Create qqq.json file. ([Guideline](https://www.mediawiki.org/wiki/Localisation#Message_documentation))
- [x] 2. Give push access to @translatewiki. ([Github Help](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/inviting-collaborators-to-a-personal-repository))
- [x] 3. Create a patch for https://gerrit.wikimedia.org/r/admin/projects/translatewiki. There is a sample patch I made for my extensions: https://gerrit.wikimedia.org/r/c/translatewiki/+/540007/

I can do 1 and 3 in the above list and I am willing to do so(making some PRs). But 1-2 does not seem to be done by me, because I not well in English. But I will try.

Thank you.

**Comment by Abijeet** [comment]
Hi @lens0021 - Let me know if you need help.

**Comment by kulttuuri** [comment]
1 and 2 are now done. Now just #3.

**Comment by lens0021** [comment]
I have uploaded Change https://gerrit.wikimedia.org/r/c/translatewiki/+/552930 a related patch set.

**Comment by kulttuuri** [comment]
Thanks! I've merged this in.

**Comment by lens0021** [comment]
The Gerrit patch is merged! Translations are available at translatewiki.net. For example, https://translatewiki.net/w/i.php?title=Special:Translate&action=translate&filter=&group=%21additions&language=es for Spanish.

**Comment by kulttuuri** [comment]
Fantastic. This thread ready to be closed?

**Comment by lens0021** [comment]
Thank you!

**Comment by lens0021** [comment]
@Abijeet Hello, can I ask you if translatewiki bot has a problem committing to this repository? Thank you

**Comment by Abijeet** [comment]
@lens0021 - Its failing at the moment.

```
ERROR: Permission to kulttuuri/DiscordNotifications.git denied to translatewiki.                                                                                                                                                                      
  fatal: Could not read from remote repository.                                                                                                                                                                                                         
  Please make sure you have the correct access rights                                                                                                                                                                                                   
  and the repository exists
```
I'll investigate further tomorrow.

**Comment by lens0021** [comment]
@kulttuuri: Could you be careful with the bug https://phabricator.wikimedia.org/T235103 and re-check the permission of tranlatewiki bot?

**Comment by Nikerabbit** [comment]
I had not accepted the invite for the bot. I have done it now.

**Comment by Abijeet** [comment]
Just pushed out the translations - https://github.com/kulttuuri/DiscordNotifications/commit/6148c98a70c9a87a5dd0e7dde981b55a73625ea9

**Comment by lens0021** [comment]
Thank you for all your efforts.
