### ISSUE TITLE
Multiple webhooks

### ISSUE THREAD

**Issue by PowerMasterAlex** [kulttuuri/DiscordNotifications#67]
Asked this on MediaWiki itself, but was asked to move it here for convenience.

Hello there. I'm trying to see if I can get Discord Notifications to send to two servers, but my attempts are not working. LocalSettings prioritizes the first webhook over the second, or ends up doing nothing at all when I tried "array". Wondering if this is possible to do in the first place, and if so, how? Thanks in advance :)

**Comment by kulttuuri** [comment]
Thanks! Did you use the `$wgDiscordAdditionalIncomingWebhookUrls` configuration option like this:

`$wgDiscordAdditionalIncomingWebhookUrls = ["https://yourUrlOne.com", "https://yourUrlTwo..."];`

**Comment by PowerMasterAlex** [comment]
Thank you, that worked! ^_^

**Comment by kulttuuri** [comment]
Glad to hear that! Closing the issue :)
