### ISSUE TITLE
Notifications for imports

### ISSUE THREAD

**Issue by charitwo** [kulttuuri/DiscordNotifications#68]
Enable reporting for notifications when articles are imported via Special:Import

**Comment by kulttuuri** [comment]
I think that this hook is suitable for this situation: https://www.mediawiki.org/wiki/Manual:Hooks/AfterImportPage

**Comment by kulttuuri** [comment]
Added in latest commit! Would be great if you could test it out again so I can bump up the version number :)

**Comment by kulttuuri** [comment]
Closed due to inactivity.
