### ISSUE TITLE
New account creation reveals IP address and email address by default

### ISSUE THREAD

**Issue by Soveia** [kulttuuri/DiscordNotifications#70]
By default, when a user creates a new account, the Discord notification will display the registration IP address and the email address, if it was set.  The instructions to disable this is buried in a readme.

This should not be default behavior given the privacy and security concerns involved. In fact, in a post-GDPR world, this feature should be removed entirely.

**Comment by kulttuuri** [comment]
Any opinions from others regarding this issue?

**Comment by charitwo** [comment]
I concur with the submitter's concerns. Privacy is super important, and there is no reason this should be enabled by default, let alone at all.

**Comment by kulttuuri** [comment]
I have now removed both of these being visible in the latest commit. I removed them from documentation and they are switched off by default, but if necessary, someone can tinker and switch them on if there is a requirement for it. But no documentation for this anymore.

Notification also still shows user full name, what do you guys think of this? Should this also be visible by default?

**Comment by Soveia** [comment]
If a user provides a full name, it will be public on first edit anyway. The page credits aren't really linked anywhere but they are publically available via &action=credits. Providing a real name replaces your username with your real name in the credits.

There are also no real technical features behind that field, so a wiki's admins could also use that field for another purpose, such a as a Discord username, in which case, displaying it in the notification would be really useful.

**Comment by kulttuuri** [comment]
Sounds reasonable. I will leave it as it is. Thank you!

Closing the issue now and creating new version of the extension with the changes :)
