### ISSUE TITLE
Feature Request: add Japanese translation?

### ISSUE THREAD

**Issue by KisaragiEffective** [kulttuuri/DiscordNotifications#72]
SSIA - I think it will be better if there is.

**Comment by kulttuuri** [comment]
Translations can be done in translatewiki website: https://translatewiki.net/ where project page is: https://translatewiki.net/w/i.php?title=Special:Translate&showMessage=discordnotifications-desc&group=mwgithub-discordnotifications&language=en&filter=&optional=1&action=translate
