### ISSUE TITLE
Some new pages being ignored

### ISSUE THREAD

**Issue by robesasu** [kulttuuri/DiscordNotifications#73]
I don't know why, but some pages are ignored and don't produce a discord message.

I've tried but haven't been able to pinpoint what causes it. As an example, the [content of this page](https://www.baka-tsuki.org/project/index.php?title=Magisterus_Bad_Trip:Volume3) doesn't generate a notification; making new pages with this text always gets ignored.

**Comment by kulttuuri** [comment]
I just copied this content to my test wiki and it worked. Weird.

- You seem though to have some extensions / such installed which might cause problems?
- What MediaWiki version do you have?
- Does the error happen when creating a page or when editing content of the page?
- Have you tried editing the extension's PHP file to view if it actually goes into the hook?

**Comment by Suika** [comment]
Slapped something like this into the *Core.php

```
534     private static function sendCurlRequest( $url, $postData ) {
535         $h = curl_init();
536         curl_setopt( $h, CURLOPT_URL, $url );
537         curl_setopt( $h, CURLOPT_POST, 1 );
538         curl_setopt( $h, CURLOPT_POSTFIELDS, $postData );
539         curl_setopt( $h, CURLOPT_RETURNTRANSFER, true );
540         curl_setopt( $h, CURLOPT_CONNECTTIMEOUT, 10 ); // Set 10 second timeout to connection
541         curl_setopt( $h, CURLOPT_TIMEOUT, 10 ); // Set global 10 second timeout to handle all data
542         curl_setopt( $h, CURLOPT_HTTPHEADER, array(
543             'Content-Type: application/json',
544             'Content-Length: ' . strlen($postData)
545             )
546         ); // Set Content-Type to application/json
547         // Commented out lines below. Using default curl settings for host and peer verification.
548         //curl_setopt ($h, CURLOPT_SSL_VERIFYHOST, 0);
549         //curl_setopt ($h, CURLOPT_SSL_VERIFYPEER, 0);
550         // ... Aaand execute the curl script!
551         $curl_output = curl_exec( $h );
552         curl_close( $h );
553         error_log("request sent\n", 3, "/tmp/php.log");
554     }
555
556     private static function sendHttpRequest( $url, $postData ) {
557         $extradata = [
558             'http' => [
559             'header'  => "Content-type: application/json",
560             'method'  => 'POST',
561             'content' => $postData,
562             ],
563         ];
564         $context = stream_context_create( $extradata );
565         $result = file_get_contents( $url, false, $context );
566         error_log("http sent\n", 3, "/tmp/php.log");
567         error_log("http sent2\n", 3, "/tmp/php.log");
568         error_log("http sent3\n", 3, "/tmp/php.log");
569         error_log($postData, 3, "/tmp/php.log");
570     }
571
```

The result was as follows:
![grafik](https://user-images.githubusercontent.com/2320837/97109033-f8e59d80-16c8-11eb-98ab-7ff006a58462.png)

**Comment by SillyBirds** [comment]
I was trying out stuff with the wiki admin and found out that if I don't fill out the summary box before posting, the discord message doesn't go through. But if I do add one, it works:

![image](https://user-images.githubusercontent.com/22528910/97109358-1ddf0e00-16d3-11eb-864a-4598670615d9.png)

![image](https://user-images.githubusercontent.com/22528910/97109372-2df6ed80-16d3-11eb-9209-c112eea14553.png)

Test4 page didn't get sent to discord, but test5 page did.

**Comment by kulttuuri** [comment]
Oh. Does this happen with other pages too if you do not fill out the summary box?

**Comment by SillyBirds** [comment]
I think I have found the combination that makes the extension ignore posts:

![image](https://user-images.githubusercontent.com/22528910/97152283-f3dc2900-1770-11eb-92a6-272c47071845.png)
![image](https://user-images.githubusercontent.com/22528910/97152314-fcccfa80-1770-11eb-8ad3-4f23c062cf8f.png)

I spent quite a bit trying out different things and discovered that for a page to be ignored, it has to have `{{: }}` code, which our wiki uses to fetch single chapter pages into a complete volume page (the ones we're having problems with) _and_ being posted with no summary.

In the example above, both pages have only one line `{{:Magisterus_Bad_Trip:Volume3_Afterword2|Afterword}}`, with test9 having no summary and test10 having one.

**Comment by kulttuuri** [comment]
Oh. Interesting. Unfortunately I cannot replicate this problem, so I am giving you some help here to replicate what the issue might be.

If you print the $result back from curl request in PHP code, what does it contain? We need to figure out if the error happens in the PHP code or in Discord API (so Discord API for some reason denies the message because it contains some special characters or something like this)

**Comment by Suika** [comment]
Ok, the gist of that test is as follows:
Printing `$curl_output` in `sendCurlRequest` results in `{"embeds": ["0"]}#`
Printing `$result` in `sendHttpRequest` results in nothing.

**Comment by lens0021** [comment]
A possible workaround: Append [`$wgUseAutomaticEditSummaries = false;`](https://www.mediawiki.org/wiki/Manual:$wgUseAutomaticEditSummaries) to your `LocalSettings.php`.

But It seems that all edit summaries include template syntax make the [substitutions](https://www.mediawiki.org/wiki/Help:Substitution) happen. In this situation, the summary with substitution was too long to request, and `PHP Warning: file_get_contents(): failed to open stream: HTTP request failed! HTTP/1.1 400 Bad Request` was occurred.

The document says "{{-transformation is done." with `Message::text()`,<sup>[[1]](https://github.com/wikimedia/mediawiki/blob/56b305afbfb1b1fff54de0a83de0875660ecd373/includes/language/Message.php#L946)</sup> therefore some(or all?) calls to `Message::text()` should be replaced with calls to `Message::plain()`.

**Comment by kulttuuri** [comment]
Great! :)
