### ISSUE TITLE
Weird webhook.

### ISSUE THREAD

**Issue by FireWolf-kPanel** [kulttuuri/DiscordNotifications#81]
I've just got that when setupping the webhook 

![image](https://user-images.githubusercontent.com/62524520/111082945-5ad56100-850b-11eb-885e-74b222845338.png)

Here is my config :

```
// Required. Name the message will appear to be sent from. Change this to whatever you wish it to be.
$wgDiscordFromName = $wgSitename;
// Avatar to use for messages. If blank, uses the webhook's default avatar.
$wgDiscordAvatarUrl = $wgFavicon;
// URL into your MediaWiki installation with the trailing /.
$wgDiscordNotificationWikiUrl = "https://wiki.plasmatale.cf/";
// Wiki script name. Leave this to default one if you do not have URL rewriting enabled.
$wgDiscordNotificationWikiUrlEnding = "";
// What method will be used to send the data to Discord server. By default this is "curl" which only works if you have the curl extension enabled. There have been cases where VisualEditor extension does not work with the curl method, so in that case the recommended solution is to use the file_get_contents method. This can be: "curl" or "file_get_contents". Default: "curl".
$wgDiscordSendMethod = "curl";
```

**Comment by lens0021** [comment]
Could you check the version of the extension your wiki uses? If the version is older than fad96aaa, you should use `$wgWikiUrl` and `$wgWikiUrlEnding` instead of `$wgDiscordNotificationWikiUrl` and `$wgDiscordNotificationWikiUrlEnding`.

**Comment by FireWolf-kPanel** [comment]
> Could you check the version of the extension your wiki uses? If the version is older than [fad96aa](https://github.com/kulttuuri/DiscordNotifications/commit/fad96aaa942040c10f9c6f1895c5a26be083f032), you should use `$wgWikiUrl` and `$wgWikiUrlEnding` instead of `$wgDiscordNotificationWikiUrl` and `$wgDiscordNotificationWikiUrlEnding`.

It worked ! Thanks!
