### ISSUE TITLE
Use of WikiPage::getRevision was deprecated in MediaWiki 1.35.

### ISSUE THREAD

**Issue by The-Voidwalker** [kulttuuri/DiscordNotifications#86]
In some cases, you should just be fine with updating getRevision calls with getRevisionRecord, but this may not work for situations where you use getPrevious, as this method does not exist in the RevisionRecord class.

**Comment by ciencia** [comment]
This has been resolved by pull #84, but it still needs to be merged :(

In the meantime you can apply the patch manually

**Comment by kulttuuri** [comment]
Merged!
