### ISSUE TITLE
Duplicated file creation notifications

### ISSUE THREAD

**Issue by GloverMist** [kulttuuri/DiscordNotifications#88]
In the latest version, notifications for new file uploads are shown twice - once as the original file notif and the second as a new page creation. I believe this issue is caused by PR #77. Thanks in advance for the help!

![image](https://user-images.githubusercontent.com/89702952/131225806-d967cddb-55c9-4ca9-b455-fce1e4f13889.png)

**Comment by kulttuuri** [comment]
I believe that in the function ```onDiscordArticleInserted``` this part no longer works:

```php
// Do not announce newly added file uploads as articles...
if ( $article->getTitle()->getNsText() == self::msg( 'discordnotifications-file-namespace' ) ) return true;
```

**Comment by kulttuuri** [comment]
Fixed in the latest commit. Can you check @GloverMist ? If all is good, I'll bump the version number up! :)

**Comment by GloverMist** [comment]
We’ve just got round to applying it and it works perfectly! Thank you very much!

**Comment by kulttuuri** [comment]
Fantastic - thank you! :)
