### ISSUE TITLE
Ghost notifications from edits not actually saved

### ISSUE THREAD

**Issue by ciencia** [kulttuuri/DiscordNotifications#91]
I've seen another ghost notification appear again. The notification seems legit, except:

- The diff is from the last edit of the page, that was done months ago
- The user name (in this case) is an IP address, that looking at contributions has no contributions
- The edit summary is not present in the comment table. The edit has never existed!

Since the actor is an IP address, this time I've looked at the webserver access logs, and I've discovered an edit attempt for that IP address, that apparently hasn't been saved.

I have [ConfirmEdit](https://www.mediawiki.org/wiki/Extension:ConfirmEdit) installed, and I suspect the IP address has posted a link that triggered the captcha, it blocked the edit, but DiscordNotifications received it anyway.

I have ConfirmEdit loaded before DiscordNotifications in LocalSettings, which apparently should fire before, unless they're using different hooks that trigger at different times...

**Comment by kulttuuri** [comment]
Sorry for taking so long to respond to this – This should now be fixed in the latest commit. Can you check it out @prodigion?
