### ISSUE TITLE
Translation issue with message MediaWiki:Discordnotifications-change-user-groups/ru

### ISSUE THREAD

**Issue by pashiko** [kulttuuri/DiscordNotifications#92]
URL: https://translatewiki.net/w/i.php?title=Special:Translate&showMessage=discordnotifications-change-user-groups&group=mwgithub-discordnotifications&language=ru

The message has only one parameter: `%s`, when the explanation has `$1`, `$2`, and `$3`. Could it be fixed somehow? Thanks!

**Comment by kulttuuri** [comment]
Should be fixed now :)
